// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkoKzhR9cKta3zn9QG58cl_sILbVl2OzA',
    appId: '1:133586309645:web:e3669c541d41ec24ad7b44',
    messagingSenderId: '133586309645',
    projectId: 'birbucukadanav2',
    authDomain: 'birbucukadanav2.firebaseapp.com',
    storageBucket: 'birbucukadanav2.firebasestorage.app',
    measurementId: 'G-0JKFC20MRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEyKwbBcLLUTOzdd6MjlkIIjk2xo9s_wQ',
    appId: '1:133586309645:android:e3c2893eb4d359fbad7b44',
    messagingSenderId: '133586309645',
    projectId: 'birbucukadanav2',
    storageBucket: 'birbucukadanav2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC66puOIaEYZeYFTmmQFe_BdBwQFThbD_o',
    appId: '1:133586309645:ios:895c6ed0157e4560ad7b44',
    messagingSenderId: '133586309645',
    projectId: 'birbucukadanav2',
    storageBucket: 'birbucukadanav2.firebasestorage.app',
    iosBundleId: 'com.example.birbucukadana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC66puOIaEYZeYFTmmQFe_BdBwQFThbD_o',
    appId: '1:133586309645:ios:895c6ed0157e4560ad7b44',
    messagingSenderId: '133586309645',
    projectId: 'birbucukadanav2',
    storageBucket: 'birbucukadanav2.firebasestorage.app',
    iosBundleId: 'com.example.birbucukadana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkoKzhR9cKta3zn9QG58cl_sILbVl2OzA',
    appId: '1:133586309645:web:15b403fae8a85697ad7b44',
    messagingSenderId: '133586309645',
    projectId: 'birbucukadanav2',
    authDomain: 'birbucukadanav2.firebaseapp.com',
    storageBucket: 'birbucukadanav2.firebasestorage.app',
    measurementId: 'G-K2ZLKKMQ9Y',
  );
}
